services:
  - type: web
    name: karan-portfolio-api
    runtime: node
    plan: free
    rootDir: backend
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: PORT
        value: 10000
      - key: NODE_ENV
        value: production
      - key: CLIENT_ORIGIN
        sync: false
      - key: SMTP_HOST
        sync: false
      - key: SMTP_PORT
        sync: false
      - key: SMTP_USER
        sync: false
      - key: SMTP_PASS
        sync: false
      - key: CONTACT_RECEIVER
        sync: false

  - type: static
    name: karan-portfolio-frontend
    plan: free
    rootDir: frontend
    buildCommand: echo "no build"
    staticPublishPath: ./
